export interface ReadOnlyLockFixture {
  readonly name: string;
  readonly command: string;
  readonly entries: readonly string[];
  readonly rule?: string;
}

export const READ_ONLY_LOCK_FIXTURES: readonly ReadOnlyLockFixture[] = [
  { name: 'exact prefix', command: 'git status --short', entries: ['git status'] },
  { name: 'prefix letters only', command: 'git statusx', entries: ['git status'], rule: 'prefix.entry' },
  { name: 'prefix tab separator', command: 'git status\t--short', entries: ['git status'], rule: 'prefix.entry' },
  { name: 'semicolon compound', command: 'git status; git log', entries: ['git status', 'git log'], rule: 'syntax.compound' },
  { name: 'and compound', command: 'git status && git log', entries: ['git status', 'git log'], rule: 'syntax.compound' },
  { name: 'or compound', command: 'git status || git log', entries: ['git status', 'git log'], rule: 'syntax.compound' },
  { name: 'pipe compound', command: 'git status | cat', entries: ['git status', 'cat'], rule: 'syntax.compound' },
  { name: 'background compound', command: 'git status &', entries: ['git status'], rule: 'syntax.compound' },
  { name: 'newline compound', command: 'git status\ngit log', entries: ['git status', 'git log'], rule: 'syntax.compound' },
  { name: 'output redirect', command: 'git status > out', entries: ['git status'], rule: 'syntax.redirection' },
  { name: 'append redirect', command: 'git status >> out', entries: ['git status'], rule: 'syntax.redirection' },
  { name: 'input redirect', command: 'cat < in', entries: ['cat'], rule: 'syntax.redirection' },
  { name: 'heredoc', command: 'cat <<EOF', entries: ['cat'], rule: 'syntax.redirection' },
  { name: 'fd redirect', command: 'git status 2> err', entries: ['git status'], rule: 'syntax.redirection' },
  { name: 'combined fd redirect', command: 'git status &> out', entries: ['git status'], rule: 'syntax.redirection' },
  { name: 'backslash newline', command: 'git sta\\\ntus', entries: ['git status'], rule: 'syntax.backslash-line' },
  { name: 'trailing backslash', command: 'git status\\', entries: ['git status'], rule: 'syntax.backslash-line' },
  { name: 'function definition', command: 'git() { rm x; }; git', entries: ['git'], rule: 'syntax.grouping' },
  { name: 'brace grouping', command: '{ git status; }', entries: ['git status'], rule: 'syntax.expansion' },
  { name: 'subshell grouping', command: '(git status)', entries: ['git status'], rule: 'syntax.grouping' },
  { name: 'N1 find function and subshell', command: 'find () ( rm -rf sub/sentinel.txt ); find', entries: ['find'], rule: 'syntax.grouping' },
  { name: 'N1 cat function and subshell', command: 'cat () ( rm -rf sub/sentinel.txt ); cat', entries: ['cat'], rule: 'syntax.grouping' },
  { name: 'N1 ls function and subshell', command: 'ls () ( rm -rf sub/sentinel.txt ); ls', entries: ['ls'], rule: 'syntax.grouping' },
  { name: 'N1 newline function invocation', command: 'find () ( rm -rf sub/sentinel.txt )\nfind', entries: ['find'], rule: 'syntax.grouping' },
  { name: 'N1 attached function name', command: 'find() ( rm -rf sub/sentinel.txt ); find', entries: ['find'], rule: 'syntax.grouping' },
  { name: 'N1 find brace body', command: 'find () { rm x; }; find', entries: ['find'], rule: 'syntax.grouping' },
  { name: 'N1 cat brace body', command: 'cat () { rm x; }; cat', entries: ['cat'], rule: 'syntax.grouping' },
  { name: 'N1 attached cat brace body', command: 'cat(){ rm x; }; cat', entries: ['cat'], rule: 'syntax.grouping' },
  { name: 'N1 function keyword paren body', command: 'function find ( rm -rf sub/sentinel.txt ); find', entries: ['function', 'find'], rule: 'syntax.grouping' },
  { name: 'N1 function keyword brace body', command: 'function find { rm x; }; find', entries: ['function', 'find'], rule: 'syntax.expansion' },
  { name: 'N1 bare brace group', command: '{ rm x; }', entries: ['{', 'rm'], rule: 'syntax.expansion' },
  { name: 'N1 bare subshell', command: '( rm x )', entries: ['rm'], rule: 'syntax.grouping' },
  { name: 'N1 grouped substitution', command: 'find $( (rm x) )', entries: ['find'], rule: 'syntax.expansion' },
  { name: 'dollar substitution', command: 'git show $(git rev-parse HEAD)', entries: ['git show'], rule: 'syntax.expansion' },
  { name: 'backtick substitution', command: 'git show `git rev-parse HEAD`', entries: ['git show'], rule: 'syntax.expansion' },
  { name: 'expansion parameter assembles find exec', command: 'find . -e${HOME:0:0}xec rm -rf {} \\;', entries: ['find', 'echo'], rule: 'syntax.expansion' },
  { name: 'expansion substitution assembles find exec', command: 'find . -e$(echo x)ec rm -rf {} \\;', entries: ['find', 'echo'], rule: 'syntax.expansion' },
  { name: 'expansion ANSI-C quote assembles find exec', command: "find . -e$'x'ec rm -rf {} \\;", entries: ['find', 'echo'], rule: 'syntax.expansion' },
  { name: 'expansion parameter assembles find delete', command: 'find sub -d${HOME:0:0}elete', entries: ['find', 'echo'], rule: 'syntax.expansion' },
  { name: 'expansion backticks assemble find exec', command: 'find . -e`echo x`ec rm {} +', entries: ['find', 'echo'], rule: 'syntax.expansion' },
  { name: 'expansion inside double quotes', command: 'find . "-e${X}xec" rm {} +', entries: ['find', 'echo'], rule: 'syntax.expansion' },
  { name: 'expansion brace assembles find exec', command: 'find . -{ex,}ec rm {} +', entries: ['find', 'echo'], rule: 'syntax.expansion' },
  { name: 'expansion tilde', command: 'find ~ -name x', entries: ['find'], rule: 'syntax.expansion' },
  { name: 'expansion star glob', command: 'find . -name *.ts', entries: ['find'], rule: 'syntax.expansion' },
  { name: 'expansion question glob', command: 'find . -name x?', entries: ['find'], rule: 'syntax.expansion' },
  { name: 'expansion bracket glob', command: 'find . -name [ab]', entries: ['find'], rule: 'syntax.expansion' },
  { name: 'expansion ANSI-C encoded find delete', command: "find sub $'\\x2ddelete'", entries: ['find'], rule: 'syntax.expansion' },
  { name: 'expansion locale quote', command: 'echo $"translated"', entries: ['echo'], rule: 'syntax.expansion' },
  { name: 'N2 delete trailing backslash', command: 'find sub -delete\\', entries: ['find'], rule: 'syntax.backslash-line' },
  { name: 'N2 delete after name trailing backslash', command: 'find sub -name x -delete\\', entries: ['find'], rule: 'syntax.backslash-line' },
  { name: 'N2 backslash final newline', command: 'find sub -delete\\\n', entries: ['find'], rule: 'syntax.backslash-line' },
  { name: 'N2 backslash joins next argument', command: 'find sub -delete\\\n -name x', entries: ['find'], rule: 'syntax.backslash-line' },
  { name: 'N2 backslash assembles delete', command: 'find sub -dele\\\nte', entries: ['find'], rule: 'syntax.backslash-line' },
  { name: 'N2 backslash assembles program', command: 'fi\\\nnd sub -delete', entries: ['find'], rule: 'syntax.backslash-line' },
  { name: 'N2 backslash inside double quotes', command: 'find sub "-dele\\\nte"', entries: ['find'], rule: 'syntax.backslash-line' },
  { name: 'N2 lone trailing backslash', command: '\\', entries: ['find'], rule: 'syntax.backslash-line' },
  { name: 'leading assignment', command: 'PAGER=cat git log', entries: ['git log'], rule: 'syntax.leading-assignment' },
  { name: 'unnamed wrapper', command: 'timeout 5 git status', entries: ['git status'], rule: 'syntax.wrapper-command' },
  { name: 'named wrapper', command: 'timeout 5 git status', entries: ['timeout'] },
  { name: 'git fetch upload-pack equals', command: 'git fetch --upload-pack=touch .', entries: ['git fetch'], rule: 'command.git-fetch-upload-pack' },
  { name: 'git fetch upload-pack separate', command: 'git fetch --upload-pack touch .', entries: ['git fetch'], rule: 'command.git-fetch-upload-pack' },
  { name: 'git ssh command', command: 'git -c core.sshCommand=touch fetch .', entries: ['git'], rule: 'command.git-config-execution' },
  { name: 'git pager', command: 'git -c core.pager=touch log', entries: ['git'], rule: 'command.git-config-execution' },
  { name: 'git alias', command: 'git -c alias.hit=!touch status', entries: ['git'], rule: 'command.git-config-execution' },
  { name: 'git fsmonitor', command: 'git -c core.fsmonitor=touch status', entries: ['git'], rule: 'command.git-config-execution' },
  { name: 'git exec path', command: 'git --exec-path=/tmp status', entries: ['git'], rule: 'command.git-exec-path' },
  { name: 'git config is always refused', command: 'git -c color.ui=false status', entries: ['git'], rule: 'command.git-config-execution' },
  { name: 'git attached config is always refused', command: 'git -ccolor.ui=false status', entries: ['git'], rule: 'command.git-config-execution' },
  { name: 'git config env is always refused', command: 'git --config-env=core.pager=PAGER status', entries: ['git'], rule: 'command.git-config-execution' },
  { name: 'git upload-pack abbreviation', command: 'git fetch --upload-p=cmd', entries: ['git fetch'], rule: 'command.git-fetch-upload-pack' },
  { name: 'git exec-path abbreviation', command: 'git --exec-p=/tmp status', entries: ['git'], rule: 'command.git-exec-path' },
  { name: 'git diff output equals', command: 'git diff --output=out', entries: ['git diff'], rule: 'command.git-output' },
  { name: 'git show output separate', command: 'git show -o out', entries: ['git show'], rule: 'command.git-output' },
  { name: 'git log output attached', command: 'git log -oout', entries: ['git log'], rule: 'command.git-output' },
  { name: 'git config before output subcommand', command: 'git -c color.ui=false diff --output=out', entries: ['git'], rule: 'command.git-config-execution' },
  { name: 'find exec', command: 'find . -exec touch x', entries: ['find'], rule: 'command.find-action' },
  { name: 'find delete', command: 'find . -delete', entries: ['find'], rule: 'command.find-action' },
  { name: 'rg pre', command: 'rg --pre cat needle', entries: ['rg'], rule: 'command.rg-pre' },
  { name: 'sed in place', command: 'sed -i s/a/b/ file', entries: ['sed'], rule: 'command.never-named' },
  { name: 'sed write command', command: "sed -e 'w out' file", entries: ['sed'], rule: 'command.never-named' },
  { name: 'sed addressed write', command: "sed '1w /dev/stderr' file", entries: ['sed'], rule: 'command.never-named' },
  { name: 'sed regex addressed write', command: "sed -n '/x/w out' file", entries: ['sed'], rule: 'command.never-named' },
  { name: 'sed command execution', command: "sed -n '1e cmd' file", entries: ['sed'], rule: 'command.never-named' },
  { name: 'awk command execution', command: `awk 'BEGIN{system("x")}'`, entries: ['awk'], rule: 'command.never-named' },
  { name: 'npm prefix redirects the project', command: 'npm run build --prefix=/tmp/evil', entries: ['npm run build'], rule: 'command.npm-prefix' },
  { name: 'git checkout path mode writes the tree', command: 'git checkout --detach main -- packages', entries: ['git checkout --detach'], rule: 'command.git-checkout-path' },
  { name: 'verdict packet accepts its exact two-part pipe', command: "printf '%s' '{}' | bash .xezar/checks/verdict-packet.sh", entries: ['printf', 'bash .xezar/checks/verdict-packet.sh'] },
  { name: 'verdict packet pipe requires its left entry', command: "printf '%s' '{}' | bash .xezar/checks/verdict-packet.sh", entries: ['bash .xezar/checks/verdict-packet.sh'], rule: 'prefix.entry' },
  { name: 'quoted operators stay text', command: 'gh pr comment 1 --body "a; b | c > d"', entries: ['gh pr comment'] },
  { name: 'quoted glob stays text', command: "find . -name '*.ts' -type f", entries: ['find'] },
  { name: 'escaped glob stays text', command: 'find . -name \\*.ts', entries: ['find'] },
  { name: 'escaped parentheses stay text', command: 'find . \\( -name a -o -name b \\)', entries: ['find'] },
  { name: 'quoted parentheses stay text', command: "find . '(' -name a ')'", entries: ['find'] },
  { name: 'comment cannot hide next command', command: "git status # it's\nrm x\n'", entries: ['git status'], rule: 'syntax.compound' },
  { name: 'grep reviewed arguments', command: 'grep -n needle file', entries: ['grep'] },
  { name: 'jq reviewed arguments', command: "jq '.items[]' file", entries: ['jq'] },
  { name: 'gh template is not a command', command: "gh pr view 1 --template '{{.title}}'", entries: ['gh pr view'] },
] as const;
