#!/usr/bin/env node
// Copy the repo's README into this package before it is built/packed.
//
// There is exactly one README (the repo root's): it is the project's GitHub front page AND the
// npm page for `@qodeca/xezar`, and those must not be allowed to drift into two documents
// saying different things about the same tool. `files` can only reference paths inside the
// package, so the one source is copied in rather than referenced out — the copy is gitignored,
// regenerated by every build, and never edited by hand.
//
// The copy is not byte-for-byte: every relative link and image source is rewritten to an
// absolute GitHub URL (#287). The root README's `docs/...` and `LICENSE` links are right on
// GitHub, but the published package contains neither, so on npmjs.com every screenshot and
// every guide link was broken. Links inside code (fenced blocks, inline code spans) are left
// alone, because there they are examples, not links.
//
// Runs as `prebuild`, so `npm run build` (and the release pipeline, which builds first) always
// packs a current copy. `check:pack` is the gate that notices if this ever stops happening.

import { readFileSync, realpathSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = path.resolve(packageRoot, '../..');

/** The branch the absolute links point at: the docs a reader follows are the current ones. */
const REF = 'main';
const IMAGE = /\.(png|jpe?g|gif|svg|webp|avif)$/i;

/** `git+https://github.com/owner/name.git` (the manifest's `repository.url`) → `https://github.com/owner/name`. */
export function githubRepoUrl(repositoryUrl) {
  const match = /github\.com[/:]([^/]+)\/([^/#?]+?)(?:\.git)?\/?$/.exec(String(repositoryUrl ?? ''));
  if (!match) throw new Error(`sync-readme: repository.url is not a GitHub repository: ${repositoryUrl}`);
  return `https://github.com/${match[1]}/${match[2]}`;
}

function isRelative(target) {
  return !(target.startsWith('#') || target.startsWith('//') || /^[a-z][a-z0-9+.-]*:/i.test(target));
}

function absolute(target, repoUrl) {
  if (!isRelative(target)) return target;
  const hash = target.indexOf('#');
  const file = path.posix.normalize(hash === -1 ? target : target.slice(0, hash)).replace(/^(\.\/|\/)+/, '');
  const fragment = hash === -1 ? '' : target.slice(hash);
  if (file === '.' || file.startsWith('../')) return target; // outside the repository: leave it for the test to flag
  if (IMAGE.test(file)) return `${repoUrl.replace('https://github.com/', 'https://raw.githubusercontent.com/')}/${REF}/${file}${fragment}`;
  return `${repoUrl}/blob/${REF}/${file}${fragment}`;
}

function rewriteProse(text, repoUrl) {
  return text
    .replace(/(\]\()(\s*)([^)\s]+)/g, (_, open, space, target) => `${open}${space}${absolute(target, repoUrl)}`)
    .replace(/(\s(?:src|href)=")([^"]+)(")/gi, (_, open, target, close) => `${open}${absolute(target, repoUrl)}${close}`)
    .replace(/^( {0,3}\[(?!\^)[^\]]+\]:[ \t]*)(\S+)/gm, (_, open, target) => `${open}${absolute(target, repoUrl)}`);
}

/**
 * The README as npm should show it: every relative Markdown link, image, reference definition and
 * HTML `src`/`href` made absolute against `repoUrl`, and everything inside code left untouched.
 */
export function absolutizeReadmeLinks(markdown, repoUrl) {
  let fence = null;
  return markdown
    .split('\n')
    .map((line) => {
      const marker = /^ {0,3}(`{3,}|~{3,})/.exec(line)?.[1];
      if (fence) {
        if (marker && marker[0] === fence[0] && marker.length >= fence.length) fence = null;
        return line;
      }
      if (marker) {
        fence = marker;
        return line;
      }
      // Odd pieces of the split are inline code spans.
      return line
        .split(/(`+[^`]*`+)/)
        .map((piece, i) => (i % 2 === 1 ? piece : rewriteProse(piece, repoUrl)))
        .join('');
    })
    .join('\n');
}

function main() {
  const manifest = JSON.parse(readFileSync(path.join(packageRoot, 'package.json'), 'utf8'));
  const readme = readFileSync(path.join(repoRoot, 'README.md'), 'utf8');
  writeFileSync(path.join(packageRoot, 'README.md'), absolutizeReadmeLinks(readme, githubRepoUrl(manifest.repository?.url)));
}

// Imported by its test for the pure functions above; only a direct run writes the copy. Real paths
// on both sides, because the script may be reached through a symlinked directory.
function isDirectRun() {
  try {
    return Boolean(process.argv[1]) && realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url));
  } catch {
    return false;
  }
}

if (isDirectRun()) main();
